In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings

# Replace the path with the correct path for your data.
data = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1)

In [65]:
data = data[:-2]

In [66]:
data = data.dropna(axis=1, how='any')
# data.info()

In [68]:
data = data.drop(['id','int_rate', 'sub_grade','url', 'zip_code','addr_state','earliest_cr_line'], axis=1)


In [81]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

y = data['loan_status']
x = data.drop('loan_status', 1)
x = pd.get_dummies(x)

rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, x, y, cv=10)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: F

array([0.96198143, 0.9655197 , 0.96309753, 0.96122061, 0.95193541,
       0.9608644 , 0.856349  , 0.96053007, 0.96055288, 0.95998195])

In [86]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

x = StandardScaler().fit_transform(x)
sklearn_pca = PCA(n_components=10)
pca_ = sklearn_pca.fit_transform(x)

print(sklearn_pca.explained_variance_ratio_)
print(pca_)

[0.1055192  0.06065753 0.0401239  0.03759784 0.03393074 0.02366239
 0.02296669 0.02248532 0.0200613  0.01998307]
[[ 3.83517495  1.55880432  1.39317882 ...  2.16563672  0.47462349
  -0.7493574 ]
 [-3.22216943 -0.66676207  1.77111624 ...  0.76498829  0.519231
  -0.26437662]
 [ 2.46130828 -3.81078738  3.1385207  ...  1.56093874  1.21659814
  -0.62937042]
 ...
 [-2.9472447  -0.08129929 -1.26471887 ... -1.0338983  -0.96546917
   1.48425406]
 [ 0.74472753 -3.3443644   0.95233212 ... -0.08146271 -0.4875309
   0.60600677]
 [-1.92054537  0.60149824 -2.67766298 ...  0.56744951 -0.28055346
  -0.60288534]]


In [88]:
import warnings
rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, pca_, y, cv=10)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: F

array([0.88459072, 0.89147729, 0.88869891, 0.90166231, 0.90398955,
       0.90194728, 0.89536679, 0.89303695, 0.8883796 , 0.8057759 ])

with 10 PCA components, the average accuracy is very close to 90%

In [95]:
y = data['loan_status']
x = data.drop('loan_status', 1)
x = pd.get_dummies(x)

columns = ['out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int','last_pymnt_amnt']

x_trim = x.drop(columns=columns)

In [96]:
rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, x_trim, y, cv=10)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: F

array([0.69805989, 0.41160267, 0.31844411, 0.35725481, 0.22144384,
       0.16969841, 0.21088128, 0.15764225, 0.22689814, 0.28907994])

the accuracy will be lower than 90%, after remove payment amount and outstanding principal information